In [ ]:
import torch

In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
# CUDA is an API developed by NVIDIA to interface GPU

In [ ]:
x = torch.randn(10)
print(x.device)

cpu


In [ ]:
# how to perform random sampling of the tensors

In [ ]:
torch.manual_seed(1234)

In [ ]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [ ]:
#generate random numbers from a statistical distribution

In [ ]:
torch.Tensor(4, 4).uniform_(0, 1) #random number from uniform distribution

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [ ]:
#now apply the distribution assuming the input values from the 
#tensor are probabilities

In [ ]:
torch.bernoulli(torch.Tensor(4, 4).uniform_(0, 1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

In [ ]:
#how to perform sampling from a multinomial distribution

In [ ]:
torch.Tensor([10, 10, 13, 10,34,45,65,67,87,89,87,34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [ ]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  3)

tensor([4, 5, 7])

In [ ]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 
                                34., 45., 65., 67., 
                                87., 89., 87., 34.]), 
                  5, replacement=True)

tensor([10,  5,  9, 10,  5])

In [ ]:
#generate random numbers from the normal distribution

In [ ]:
torch.normal(mean=torch.arange(1., 11.), 
             std=torch.arange(1, 0, -0.1))

tensor([1.5236, 2.2441, 2.7375, 3.9521, 5.4380, 5.5158, 8.2489, 8.1645, 9.0575,
        9.8627])

In [ ]:
torch.normal(mean=0.5, 
             std=torch.arange(1., 6.))

tensor([ 1.1144,  0.0361,  1.2766, -1.3999, -0.1648])

In [ ]:
torch.normal(mean=0.5, 
             std=torch.arange(0.2,0.6))

tensor([-0.0844])

In [ ]:
#computing the descriptive statistics: mean
torch.mean(torch.tensor([10., 10., 13., 10., 34., 
                         45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [ ]:
# mean across rows and across columns
d = torch.randn(4, 5)
d

tensor([[-1.6406,  0.9295,  1.2907,  0.2612,  0.9711],
        [ 0.3551,  0.8562, -0.3635, -0.1552, -1.2282],
        [ 1.2445,  1.1750, -0.2217, -2.0901, -1.2658],
        [-1.8761, -0.6066,  0.7470,  0.4811,  0.6234]])

In [ ]:
torch.mean(d,dim=0)

tensor([-0.4793,  0.5885,  0.3631, -0.3757, -0.2249])

In [ ]:
torch.mean(d,dim=1)

tensor([ 0.3624, -0.1071, -0.2316, -0.1262])

In [ ]:
#compute median
torch.median(d,dim=0)

torch.return_types.median(
values=tensor([-1.6406,  0.8562, -0.2217, -0.1552, -1.2282]),
indices=tensor([0, 1, 2, 1, 1]))

In [ ]:
torch.median(d,dim=1)

torch.return_types.median(
values=tensor([ 0.9295, -0.1552, -0.2217,  0.4811]),
indices=tensor([1, 3, 2, 3]))

In [ ]:
# compute the mode
torch.mode(d)

torch.return_types.mode(
values=tensor([-1.6406, -1.2282, -2.0901, -1.8761]),
indices=tensor([0, 4, 3, 0]))

In [ ]:
torch.mode(d,dim=0)

torch.return_types.mode(
values=tensor([-1.8761, -0.6066, -0.3635, -2.0901, -1.2658]),
indices=tensor([3, 3, 1, 2, 2]))

In [ ]:
torch.mode(d,dim=1)

torch.return_types.mode(
values=tensor([-1.6406, -1.2282, -2.0901, -1.8761]),
indices=tensor([0, 4, 3, 0]))

In [ ]:
#compute the standard deviation
torch.std(d)

tensor(1.0944)

In [ ]:
torch.std(d,dim=0)

tensor([1.5240, 0.8083, 0.7911, 1.1730, 1.1889])

In [ ]:
torch.std(d,dim=1)

tensor([1.1807, 0.7852, 1.4732, 1.1165])

In [ ]:
#compute variance
torch.var(d)

tensor(1.1978)

In [ ]:
torch.var(d,dim=0)

tensor([2.3224, 0.6534, 0.6259, 1.3758, 1.4134])

In [ ]:
torch.var(d,dim=1)

tensor([1.3940, 0.6166, 2.1703, 1.2466])

In [ ]:
# compute min and max
torch.min(d)

tensor(-2.0901)

In [ ]:
torch.min(d,dim=0)

torch.return_types.min(
values=tensor([-1.8761, -0.6066, -0.3635, -2.0901, -1.2658]),
indices=tensor([3, 3, 1, 2, 2]))

In [ ]:
torch.min(d,dim=1)

torch.return_types.min(
values=tensor([-1.6406, -1.2282, -2.0901, -1.8761]),
indices=tensor([0, 4, 3, 0]))

In [ ]:
torch.max(d)

tensor(1.2907)

In [ ]:
torch.max(d,dim=0)

torch.return_types.max(
values=tensor([1.2445, 1.1750, 1.2907, 0.4811, 0.9711]),
indices=tensor([2, 2, 0, 3, 0]))

In [ ]:
torch.max(d,dim=1)

torch.return_types.max(
values=tensor([1.2907, 0.8562, 1.2445, 0.7470]),
indices=tensor([2, 1, 0, 2]))

In [ ]:
# sorting a tensor
torch.sort(d)

torch.return_types.sort(
values=tensor([[-1.6406,  0.2612,  0.9295,  0.9711,  1.2907],
        [-1.2282, -0.3635, -0.1552,  0.3551,  0.8562],
        [-2.0901, -1.2658, -0.2217,  1.1750,  1.2445],
        [-1.8761, -0.6066,  0.4811,  0.6234,  0.7470]]),
indices=tensor([[0, 3, 1, 4, 2],
        [4, 2, 3, 0, 1],
        [3, 4, 2, 1, 0],
        [0, 1, 3, 4, 2]]))

In [ ]:
torch.sort(d,dim=0)

torch.return_types.sort(
values=tensor([[-1.8761, -0.6066, -0.3635, -2.0901, -1.2658],
        [-1.6406,  0.8562, -0.2217, -0.1552, -1.2282],
        [ 0.3551,  0.9295,  0.7470,  0.2612,  0.6234],
        [ 1.2445,  1.1750,  1.2907,  0.4811,  0.9711]]),
indices=tensor([[3, 3, 1, 2, 2],
        [0, 1, 2, 1, 1],
        [1, 0, 3, 0, 3],
        [2, 2, 0, 3, 0]]))

In [ ]:
torch.sort(d,dim=0,descending=True)

torch.return_types.sort(
values=tensor([[ 1.2445,  1.1750,  1.2907,  0.4811,  0.9711],
        [ 0.3551,  0.9295,  0.7470,  0.2612,  0.6234],
        [-1.6406,  0.8562, -0.2217, -0.1552, -1.2282],
        [-1.8761, -0.6066, -0.3635, -2.0901, -1.2658]]),
indices=tensor([[2, 2, 0, 3, 0],
        [1, 0, 3, 0, 3],
        [0, 1, 2, 1, 1],
        [3, 3, 1, 2, 2]]))

In [ ]:
torch.sort(d,dim=1,descending=True)

torch.return_types.sort(
values=tensor([[ 1.2907,  0.9711,  0.9295,  0.2612, -1.6406],
        [ 0.8562,  0.3551, -0.1552, -0.3635, -1.2282],
        [ 1.2445,  1.1750, -0.2217, -1.2658, -2.0901],
        [ 0.7470,  0.6234,  0.4811, -0.6066, -1.8761]]),
indices=tensor([[2, 4, 1, 3, 0],
        [1, 0, 3, 2, 4],
        [0, 1, 2, 4, 3],
        [2, 4, 3, 1, 0]]))

In [ ]:
from torch.autograd import Variable

In [ ]:
Variable(torch.ones(2,2),requires_grad=True)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
a, b = 12,23
x1 = Variable(torch.randn(a,b),
            requires_grad=True)
x2 = Variable(torch.randn(a,b),
            requires_grad=True)
x3 =Variable(torch.randn(a,b),
            requires_grad=True)

In [ ]:
c = x1 * x2
d = a + x3
e = torch.sum(d)

e.backward()

print(e)

tensor(3278.1235, grad_fn=<SumBackward0>)


In [ ]:
x1.data

tensor([[-4.9545e-02,  6.2245e-01,  1.6573e-01,  3.1583e-01,  2.4915e-01,
         -4.9784e-01,  2.9079e+00,  1.6201e+00, -6.4459e-01, -1.9885e-02,
          1.6222e+00,  1.4239e+00,  9.0691e-01,  7.6310e-02,  1.1225e+00,
         -1.2433e+00, -6.7258e-01,  8.8433e-01, -6.6589e-01, -7.3347e-01,
         -2.7599e-01,  5.5485e-01, -1.9303e+00],
        [-7.6389e-01, -9.9300e-01,  1.4080e+00,  2.5969e-01,  8.0760e-01,
         -1.2618e+00, -7.7109e-01, -1.8497e+00,  2.2400e-01,  2.2088e-01,
         -8.2452e-01, -2.5581e-02, -1.9850e+00, -3.7880e-01, -1.5030e+00,
         -2.9808e+00,  5.1149e-01, -9.3890e-01, -1.9421e+00,  9.8052e-01,
         -7.4463e-02, -7.1181e-01,  1.6136e+00],
        [-1.8821e+00, -1.8542e+00, -2.5013e-01,  1.6023e-01,  2.0778e-01,
          1.1879e+00, -7.3204e-01,  1.3668e+00,  9.4616e-01,  6.1018e-01,
         -1.1084e-01, -2.5730e-01,  6.3652e-01, -4.8517e-01, -7.1437e-01,
         -6.0011e-02,  2.5377e-01,  8.2522e-02,  1.0270e+00,  7.0402e-02,
          4.29

In [ ]:
x2.data

tensor([[-7.5597e-01, -1.1689e+00, -9.3890e-01,  8.8566e-01,  1.3764e+00,
         -7.8276e-01,  2.2200e-01,  7.3758e-02, -6.9147e-01, -5.1308e-01,
          1.1427e+00, -1.0126e+00,  1.1602e-01, -1.0350e+00,  1.0803e+00,
         -7.9977e-01, -9.1219e-02,  5.0242e-01, -4.5173e-01, -4.8067e-01,
          5.9066e-01,  1.6343e-01, -3.1368e-02],
        [ 4.4646e-01, -2.1036e+00, -1.8971e+00,  1.4661e+00,  6.1199e-01,
          7.9935e-01,  9.3007e-01,  1.2819e+00, -6.2896e-01,  3.0550e-01,
          5.8429e-01, -2.1502e+00,  4.1505e-01,  3.1579e-03, -3.8580e-01,
          5.7681e-01, -1.1972e+00, -2.4006e-01, -1.3253e+00,  1.1415e+00,
         -4.4164e-01,  3.4923e-01, -1.6730e+00],
        [ 1.7173e+00, -1.0184e+00,  1.1152e+00, -5.0580e-01,  1.7331e-01,
         -6.8128e-01,  2.5642e-02,  1.2838e+00,  1.3107e+00,  1.4736e+00,
          1.3023e+00, -1.4379e+00, -1.7115e+00, -8.0051e-01,  1.4921e+00,
         -1.0768e-01,  1.8001e+00,  9.7892e-01, -5.9166e-01,  8.5103e-02,
          7.52

In [ ]:
x3.data

tensor([[ 0.2499,  0.2458,  0.1029, -0.6494, -0.3258,  0.8149,  0.4049,  0.2481,
          0.4841,  0.3293, -1.2471,  0.2117,  1.4315,  0.0502, -0.3668,  0.8378,
         -0.7901,  0.0267, -0.3120,  2.4534,  0.7926,  0.2382, -0.5245],
        [-0.2131, -2.0323, -0.3952,  0.7286,  1.3579,  1.3583, -0.5818, -0.3204,
         -0.7242, -1.4629,  0.6109,  0.2401, -0.5455,  2.9154, -0.1985,  0.7507,
         -0.0390, -0.8322,  0.1364,  0.4531, -0.1112,  1.0307, -1.1862],
        [-0.9696,  0.1508,  0.9814, -1.9638, -0.2218,  0.1477, -0.1875,  0.9963,
          0.3611,  0.0238,  1.7371, -0.7392, -0.1709,  1.2120,  0.9385,  0.3245,
         -1.7054,  0.7467, -1.4787, -0.2400,  0.4558, -1.0911,  0.1566],
        [-1.0629,  0.7770,  0.4003, -0.7194,  0.3499, -0.3935, -0.3622, -3.4058,
         -0.1108, -0.7741,  0.9103, -0.0961, -0.6697, -0.1985, -1.1560, -0.7709,
         -0.4655, -0.3847, -0.4364, -0.7429, -0.5210, -0.8078, -0.4448],
        [ 1.4265,  0.2566,  0.4157,  1.7485, -0.5296, -0.713

In [ ]:
from torch import FloatTensor
from torch.autograd import Variable

a = Variable(FloatTensor([5]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (12, 53, 91, 73)]

w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
Loss = (10 - d)

Loss.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to Loss: {gradient}")

Gradient of w1 w.r.t to Loss: -455.0
Gradient of w2 w.r.t to Loss: -365.0
Gradient of w3 w.r.t to Loss: -60.0
Gradient of w4 w.r.t to Loss: -265.0


In [ ]:
# Using forward pass
def forward(x):
    return x * w

In [ ]:
import torch
from torch.autograd import Variable

x_data = [11.0, 22.0, 33.0]
y_data = [21.0, 14.0, 64.0]

w = Variable(torch.Tensor([1.0]),  requires_grad=True)  # Any random value

# Before training
print("predict (before training)",  4, forward(4).data[0])

predict (before training) 4 tensor(4.)


In [ ]:
# define the Loss function
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y) * (y_pred - y)

In [ ]:
# Run the Training loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.01 * w.grad.data

        # Manually set the gradients to zero after updating weights
        w.grad.data.zero_()

    print("progress:", epoch, l.data[0])

	grad:  11.0 21.0 tensor(-220.)
	grad:  22.0 14.0 tensor(2481.6001)
	grad:  33.0 64.0 tensor(-51303.6484)
progress: 0 tensor(604238.8125)
	grad:  11.0 21.0 tensor(118461.7578)
	grad:  22.0 14.0 tensor(-671630.6875)
	grad:  33.0 64.0 tensor(13114108.)
progress: 1 tensor(3.9481e+10)
	grad:  11.0 21.0 tensor(-30279010.)
	grad:  22.0 14.0 tensor(1.7199e+08)
	grad:  33.0 64.0 tensor(-3.3589e+09)
progress: 2 tensor(2.5900e+15)
	grad:  11.0 21.0 tensor(7.7553e+09)
	grad:  22.0 14.0 tensor(-4.4050e+10)
	grad:  33.0 64.0 tensor(8.6030e+11)
progress: 3 tensor(1.6991e+20)
	grad:  11.0 21.0 tensor(-1.9863e+12)
	grad:  22.0 14.0 tensor(1.1282e+13)
	grad:  33.0 64.0 tensor(-2.2034e+14)
progress: 4 tensor(1.1146e+25)
	grad:  11.0 21.0 tensor(5.0875e+14)
	grad:  22.0 14.0 tensor(-2.8897e+15)
	grad:  33.0 64.0 tensor(5.6436e+16)
progress: 5 tensor(7.3118e+29)
	grad:  11.0 21.0 tensor(-1.3030e+17)
	grad:  22.0 14.0 tensor(7.4013e+17)
	grad:  33.0 64.0 tensor(-1.4455e+19)
progress: 6 tensor(4.7966e+34)
	

In [ ]:
# After training
print("predict (after training)",  4, forward(4).data[0])

predict (after training) 4 tensor(-9.2687e+24)


In [ ]:
z = Variable(torch.Tensor(4, 4).uniform_(-5, 5))
print(z)

tensor([[-0.3071, -3.6691, -2.8417, -1.1818],
        [-1.4654, -0.4344, -2.0130, -2.3842],
        [ 1.3962,  1.4962, -2.0996,  1.8881],
        [-1.9797,  0.2337, -1.0308,  0.1266]])


In [ ]:
print('Requires Gradient : %s ' % (z.requires_grad))
print('Volatile : %s ' % (z.volatile))
print('Gradient : %s ' % (z.grad))
print(z.data)

Requires Gradient : False 
Volatile : False 
Gradient : None 
tensor([[-0.3071, -3.6691, -2.8417, -1.1818],
        [-1.4654, -0.4344, -2.0130, -2.3842],
        [ 1.3962,  1.4962, -2.0996,  1.8881],
        [-1.9797,  0.2337, -1.0308,  0.1266]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: volatile was removed (Variable.volatile is always False)
  


In [ ]:
x = Variable(torch.Tensor(4, 4).uniform_(-4, 5))
y = Variable(torch.Tensor(4, 4).uniform_(-3, 2))
# matrix multiplication
z = torch.mm(x, y)
print(z.size())

torch.Size([4, 4])


In [ ]:
x.data

tensor([[ 4.1714, -1.3202,  4.5641,  0.2945],
        [-2.5585,  2.0775,  1.0064,  4.9148],
        [ 3.9464, -3.6807,  4.3685,  4.6255],
        [ 2.8453,  0.2704,  4.8619,  0.7903]])

In [ ]:
#tensor operations

In [ ]:
mat1 = torch.FloatTensor(4,4).uniform_(0,1)
mat1

tensor([[0.9002, 0.9188, 0.1386, 0.3701],
        [0.1947, 0.2268, 0.9587, 0.2615],
        [0.7256, 0.7673, 0.5667, 0.1863],
        [0.4642, 0.4016, 0.9981, 0.8452]])

In [ ]:
mat2 = torch.FloatTensor(4,4).uniform_(0,1)
mat2

tensor([[0.4962, 0.4947, 0.8344, 0.6721],
        [0.1182, 0.5997, 0.8990, 0.8252],
        [0.1466, 0.1093, 0.8135, 0.9047],
        [0.2486, 0.1873, 0.6159, 0.2471]])

In [ ]:
vec1 = torch.FloatTensor(4).uniform_(0,1)
vec1

tensor([0.7582, 0.6879, 0.8949, 0.3995])

In [ ]:
# scalar addition

In [ ]:
mat1 + 10.5

tensor([[11.4002, 11.4188, 10.6386, 10.8701],
        [10.6947, 10.7268, 11.4587, 10.7615],
        [11.2256, 11.2673, 11.0667, 10.6863],
        [10.9642, 10.9016, 11.4981, 11.3452]])

In [ ]:
# scalar subtraction

In [ ]:
mat2 - 0.20

tensor([[ 0.2962,  0.2947,  0.6344,  0.4721],
        [-0.0818,  0.3997,  0.6990,  0.6252],
        [-0.0534, -0.0907,  0.6135,  0.7047],
        [ 0.0486, -0.0127,  0.4159,  0.0471]])

In [ ]:
# vector and matrix addition

In [ ]:
mat1 + vec1

tensor([[1.6584, 1.6067, 1.0335, 0.7695],
        [0.9530, 0.9147, 1.8537, 0.6610],
        [1.4839, 1.4553, 1.4616, 0.5858],
        [1.2224, 1.0895, 1.8931, 1.2446]])

In [ ]:
mat2 + vec1

tensor([[1.2544, 1.1826, 1.7293, 1.0716],
        [0.8764, 1.2876, 1.7939, 1.2247],
        [0.9049, 0.7972, 1.7084, 1.3042],
        [1.0068, 0.8752, 1.5108, 0.6466]])

In [ ]:
# matrix-matrix addition

In [ ]:
mat1 + mat2

tensor([[1.3963, 1.4135, 0.9730, 1.0422],
        [0.3129, 0.8265, 1.8577, 1.0867],
        [0.8722, 0.8766, 1.3802, 1.0910],
        [0.7127, 0.5888, 1.6141, 1.0923]])

In [ ]:
mat1 * mat1

tensor([[0.8103, 0.8442, 0.0192, 0.1370],
        [0.0379, 0.0514, 0.9192, 0.0684],
        [0.5265, 0.5888, 0.3211, 0.0347],
        [0.2155, 0.1613, 0.9963, 0.7143]])

In [ ]:
# about Bernoulli distribution

In [ ]:
from torch.distributions.bernoulli import Bernoulli

In [ ]:
dist = Bernoulli(torch.tensor([0.3,0.6,0.9]))

In [ ]:
dist.sample() #sample is binary, it takes 1 with p and 0 with 1-p

tensor([0., 1., 0.])

In [ ]:
#Creates a Bernoulli distribution parameterized by probs 
#Samples are binary (0 or 1). They take the value 1 with probability p 
#and 0 with probability 1 - p.

In [ ]:
from torch.distributions.beta import Beta

In [ ]:
dist = Beta(torch.tensor([0.5]), torch.tensor([0.5]))
dist

Beta()

In [ ]:
dist.sample()

tensor([0.6771])

In [ ]:
from torch.distributions.binomial import Binomial

In [ ]:
dist = Binomial(100, torch.tensor([0 , .2, .8, 1]))

In [ ]:
dist.sample()

tensor([  0.,  21.,  83., 100.])

In [ ]:
# 100- count of trials
# 0, 0.2, 0.8 and 1 are event probabilities

In [ ]:
from torch.distributions.categorical import Categorical

In [ ]:
dist = Categorical(torch.tensor([ 0.20, 0.20, 0.20, 0.20, 0.20 ]))
dist

Categorical(probs: torch.Size([5]))

In [ ]:
dist.sample()

tensor(2)

In [ ]:
# 0.20, 0.20, 0.20, 0.20,0.20 event probabilities

In [ ]:
# Laplace distribution parameterized by loc and ‘scale’.

In [ ]:
from torch.distributions.laplace import Laplace

In [ ]:
dist = Laplace(torch.tensor([10.0]), torch.tensor([0.990]))
dist

Laplace(loc: tensor([10.]), scale: tensor([0.9900]))

In [ ]:
dist.sample()

tensor([9.6554])

In [ ]:
#Normal (Gaussian) distribution parameterized by loc and ‘scale’.

In [ ]:
from torch.distributions.normal import Normal

In [ ]:
dist = Normal(torch.tensor([100.0]), torch.tensor([10.0]))
dist

Normal(loc: tensor([100.]), scale: tensor([10.]))

In [ ]:
dist.sample()

tensor([84.3435])