In [1]:
from __future__ import print_function
import torch

In [2]:
torch.version.__version__

'1.12.1+cu113'

# PyTorch basics

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are
defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful
utilities.
It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute
capability >= 2.0.

In [3]:
x = [12,23,34,45,56,67,78]

In [8]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [9]:
scalar.ndim

0

In [14]:
scalar.item()

10

In [11]:
#vector
vector = torch.tensor([5,5])
vector

tensor([5, 5])

In [12]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [17]:
# Matrix
matrix = torch.tensor([[4, 5], 
                       [10, 110]])
matrix

tensor([[  4,   5],
        [ 10, 110]])

In [18]:
matrix.ndim

2

In [19]:
matrix.shape

torch.Size([2, 2])

In [20]:
# Tensor is multidimensional
tensor = torch.tensor([[[4,64, 5,4], 
                       [10,20,30, 110],
                        [45,34,67,40],
                        [56,67,89,90]]])
tensor

tensor([[[  4,  64,   5,   4],
         [ 10,  20,  30, 110],
         [ 45,  34,  67,  40],
         [ 56,  67,  89,  90]]])

In [21]:
tensor.ndim

3

In [22]:
tensor.shape

torch.Size([1, 4, 4])

In [23]:
tensor.dtype

torch.int64

In [24]:
tensor.device

device(type='cpu')

In [133]:
tensor

tensor([[[  4,  64,   5,   4],
         [ 10,  20,  30, 110],
         [ 45,  34,  67,  40],
         [ 56,  67,  89,  90]]])

In [25]:
# Element-wise matrix mutlication
tensor * tensor

tensor([[[   16,  4096,    25,    16],
         [  100,   400,   900, 12100],
         [ 2025,  1156,  4489,  1600],
         [ 3136,  4489,  7921,  8100]]])

In [26]:
torch.matmul(tensor, tensor)

tensor([[[ 1105,  1974,  2631,  7616],
         [ 7750,  9430, 12450, 13340],
         [ 5775,  8518,  9294, 10200],
         [ 9939, 13980, 16263, 19254]]])

In [28]:
tensor @ tensor

tensor([[[ 1105,  1974,  2631,  7616],
         [ 7750,  9430, 12450, 13340],
         [ 5775,  8518,  9294, 10200],
         [ 9939, 13980, 16263, 19254]]])

In [32]:
# for reproducing the same sample
torch.manual_seed(123)
torch.rand(10)

tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
        0.7264])

In [33]:
torch.rand(10)

tensor([0.3153, 0.6871, 0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274, 0.3821,
        0.6605])

In [35]:
torch.manual_seed(123)
torch.rand(10)

tensor([0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665, 0.1366, 0.1025, 0.1841,
        0.7264])

In [4]:
torch.is_tensor(x)

False

In [5]:
torch.is_storage(x)

False

In [6]:
y = torch.randn(1,2,3,4,5)

In [ ]:
torch.is_tensor(y)

True

In [ ]:
torch.is_storage(y)

False

In [ ]:
torch.numel(y) # the total number of elements in the input Tensor

120

In [ ]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.numel(torch.zeros(4,4))

16

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [ ]:
type(x)

list

In [ ]:
import numpy as np
x1 = np.array(x)

In [ ]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [ ]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [ ]:
torch.linspace(2, 10, steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [ ]:
torch.linspace(-10, 10, steps=15)

tensor([-1.0000e+01, -8.5714e+00, -7.1429e+00, -5.7143e+00, -4.2857e+00,
        -2.8571e+00, -1.4286e+00, -2.3842e-07,  1.4286e+00,  2.8571e+00,
         4.2857e+00,  5.7143e+00,  7.1429e+00,  8.5714e+00,  1.0000e+01])

In [ ]:
torch.logspace(start=-10, end=10, steps=15) #logarithmic spacing

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [ ]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [ ]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
# random numbers from a uniform distribution between the values 
# 0 and 1
torch.rand(10)

tensor([0.1408, 0.4445, 0.4251, 0.2663, 0.3743, 0.4784, 0.3760, 0.1876, 0.2151,
        0.6876])

In [ ]:
torch.rand(4, 5) 
# random values between 0 and 1 and fillied with a matrix of 
# size rows 4 and columns 5

tensor([[0.2733, 0.0302, 0.8835, 0.9537, 0.9662],
        [0.6296, 0.3106, 0.4029, 0.8133, 0.1697],
        [0.8578, 0.6517, 0.0440, 0.6197, 0.9889],
        [0.8614, 0.6288, 0.2158, 0.4593, 0.2444]])

In [ ]:
#random numbers from a normal distribution, 
#with mean =0 and standard deviation =1
torch.randn(10)

tensor([ 1.0115, -0.7502,  1.1994,  0.8736,  0.5633, -0.7702,  0.1826, -1.9931,
         0.5159,  0.1521])

In [ ]:
torch.randn(4, 5)

tensor([[ 0.3744,  2.1839, -1.8229,  1.0682,  1.5394],
        [ 0.9689, -1.3085, -0.3300,  0.3960, -0.6079],
        [ 2.3485,  1.2880,  0.6754, -2.0426, -0.3121],
        [-0.4897, -1.5335,  0.0467, -0.6213,  1.7185]])

In [ ]:
#selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([1, 6, 3, 2, 0, 8, 4, 5, 7, 9])

In [ ]:
#usage of range function 
torch.arange(10, 40,2) #step size 2

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
torch.arange(10,40) #step size 1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
d = torch.randn(4, 5)
d

tensor([[ 1.0085, -0.8545, -0.6958,  1.6716, -0.0118],
        [ 0.2134,  1.1154, -0.6426, -1.3651, -1.5724],
        [ 0.2452,  0.8356,  2.0297, -0.2397,  0.8560],
        [ 0.9786, -0.8538, -0.6449,  0.3903,  1.5966]])

In [ ]:
torch.argmin(d,dim=1)

tensor([1, 4, 3, 1])

In [ ]:
torch.argmax(d,dim=1)

tensor([3, 1, 2, 4])

In [ ]:
# create a 2dtensor filled with values as 0
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# create a 1d tensor filled with values as 0
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#indexing and performing operation on the tensors
x = torch.randn(4,5)

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#concatenate two tensors
torch.cat((x,x))

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280],
        [-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#concatenate n times based on array size
torch.cat((x,x,x))

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280],
        [-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280],
        [-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#concatenate n times based on array size, over column
torch.cat((x,x,x),1)

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114, -1.5343, -1.3533, -0.8621,
         -1.1674, -0.1114, -1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379,  0.2790,  0.0463,  1.5364,
         -0.1287,  0.6379,  0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602, -0.4542,  0.5196,  0.2335,
         -0.5135, -0.6602, -0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280, -0.6930,  0.0541, -0.8463,
         -0.4498, -0.0280, -0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#concatenate n times based on array size, over rows
torch.cat((x,x),0)

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280],
        [-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#how to split a tensor among small chunks

In [ ]:
help(torch.chunk)

Help on built-in function chunk in module torch:

chunk(...)
    chunk(input, chunks, dim=0) -> List of Tensors
    
    Attempts to split a tensor into the specified number of chunks. Each chunk is a view of
    the input tensor.
    
    
    .. note::
    
        This function may return less then the specified number of chunks!
    
    .. seealso::
    
        :func:`torch.tensor_split` a function that always returns exactly the specified number of chunks
    
    If the tensor size along the given dimesion :attr:`dim` is divisible by :attr:`chunks`,
    all returned chunks will be the same size.
    If the tensor size along the given dimension :attr:`dim` is not divisible by :attr:`chunks`,
    all returned chunks will be the same size, except the last one.
    If such division is not possible, this function may return less
    than the specified number of chunks.
    
    Arguments:
        input (Tensor): the tensor to split
        chunks (int): number of chunks to return
  

In [ ]:
a = torch.randn(4, 4)
print(a)
torch.chunk(a,2)

tensor([[-0.5899, -1.3432, -1.0576, -0.1696],
        [ 0.2623, -0.1585,  1.0178, -0.2216],
        [-1.1716, -1.2771,  0.8073, -0.7717],
        [ 0.1768,  0.6423, -0.3200, -0.0480]])


(tensor([[-0.5899, -1.3432, -1.0576, -0.1696],
         [ 0.2623, -0.1585,  1.0178, -0.2216]]),
 tensor([[-1.1716, -1.2771,  0.8073, -0.7717],
         [ 0.1768,  0.6423, -0.3200, -0.0480]]))

In [ ]:
torch.chunk(a,2,0)

(tensor([[-0.5899, -1.3432, -1.0576, -0.1696],
         [ 0.2623, -0.1585,  1.0178, -0.2216]]),
 tensor([[-1.1716, -1.2771,  0.8073, -0.7717],
         [ 0.1768,  0.6423, -0.3200, -0.0480]]))

In [ ]:
torch.chunk(a,2,1)

(tensor([[-0.5899, -1.3432],
         [ 0.2623, -0.1585],
         [-1.1716, -1.2771],
         [ 0.1768,  0.6423]]), tensor([[-1.0576, -0.1696],
         [ 1.0178, -0.2216],
         [ 0.8073, -0.7717],
         [-0.3200, -0.0480]]))

In [ ]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [ ]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 1, 
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [ ]:
 torch.LongTensor([[0,0],[1,0]]) 
#the 1D tensor containing the indices to index

tensor([[0, 0],
        [1, 0]])

In [ ]:
a = torch.randn(4, 4)
print(a)

tensor([[-0.9183, -2.3470,  1.5208, -0.1585],
        [-0.6741, -0.6297,  0.2581, -1.1954],
        [ 1.0443, -1.3408,  0.7863, -0.6056],
        [-0.6946, -0.5963,  0.1936, -2.0625]])


In [ ]:
indices = torch.LongTensor([0, 2])

In [ ]:
torch.index_select(a, 0, indices)

tensor([[-0.9183, -2.3470,  1.5208, -0.1585],
        [ 1.0443, -1.3408,  0.7863, -0.6056]])

In [ ]:
torch.index_select(a, 1, indices)

tensor([[-0.9183,  1.5208],
        [-0.6741,  0.2581],
        [ 1.0443,  0.7863],
        [-0.6946,  0.1936]])

In [ ]:
#identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [ ]:
torch.nonzero(torch.Tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [ ]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [ ]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

In [ ]:
torch.zeros(3,2,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.zeros(3,2,4).size()

torch.Size([3, 2, 4])

In [ ]:
#how to reshape the tensors along a new dimension

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
x.t() #transpose is one option to change the shape of the tensor

tensor([[-1.5343,  0.2790, -0.4542, -0.6930],
        [-1.3533,  0.0463,  0.5196,  0.0541],
        [-0.8621,  1.5364,  0.2335, -0.8463],
        [-1.1674, -0.1287, -0.5135, -0.4498],
        [-0.1114,  0.6379, -0.6602, -0.0280]])

In [ ]:
# transpose partially based on rows and columns

In [ ]:
x.transpose(1,0)

tensor([[-1.5343,  0.2790, -0.4542, -0.6930],
        [-1.3533,  0.0463,  0.5196,  0.0541],
        [-0.8621,  1.5364,  0.2335, -0.8463],
        [-1.1674, -0.1287, -0.5135, -0.4498],
        [-0.1114,  0.6379, -0.6602, -0.0280]])

In [ ]:
# how to remove a dimension from a tensor

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
torch.unbind(x,1) #dim=1 removing a column

(tensor([-1.5343,  0.2790, -0.4542, -0.6930]),
 tensor([-1.3533,  0.0463,  0.5196,  0.0541]),
 tensor([-0.8621,  1.5364,  0.2335, -0.8463]),
 tensor([-1.1674, -0.1287, -0.5135, -0.4498]),
 tensor([-0.1114,  0.6379, -0.6602, -0.0280]))

In [ ]:
torch.unbind(x) #dim=0 removing a row

(tensor([-1.5343, -1.3533, -0.8621, -1.1674, -0.1114]),
 tensor([ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379]),
 tensor([-0.4542,  0.5196,  0.2335, -0.5135, -0.6602]),
 tensor([-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]))

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
#how to compute the basic mathematrical functions

In [ ]:
torch.abs(torch.FloatTensor([-10, -23, 3.000]))

tensor([10., 23.,  3.])

In [ ]:
#adding value to the existing tensor, scalar addition
torch.add(x,20)

tensor([[18.4657, 18.6467, 19.1379, 18.8326, 19.8886],
        [20.2790, 20.0463, 21.5364, 19.8713, 20.6379],
        [19.5458, 20.5196, 20.2335, 19.4865, 19.3398],
        [19.3070, 20.0541, 19.1537, 19.5502, 19.9720]])

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
# scalar multiplication
torch.mul(x,2)

tensor([[-3.0686, -2.7065, -1.7242, -2.3349, -0.2227],
        [ 0.5581,  0.0926,  3.0727, -0.2575,  1.2757],
        [-0.9084,  1.0392,  0.4670, -1.0270, -1.3203],
        [-1.3859,  0.1082, -1.6926, -0.8995, -0.0560]])

In [ ]:
x

tensor([[-1.5343, -1.3533, -0.8621, -1.1674, -0.1114],
        [ 0.2790,  0.0463,  1.5364, -0.1287,  0.6379],
        [-0.4542,  0.5196,  0.2335, -0.5135, -0.6602],
        [-0.6930,  0.0541, -0.8463, -0.4498, -0.0280]])

In [ ]:
# how do we represent the equation in the form of a tensor

In [ ]:
# y = intercept + (beta * x)

In [ ]:
intercept = torch.randn(1)
intercept

tensor([-1.1444])

In [ ]:
x = torch.randn(2, 2)
x

tensor([[ 1.3517, -0.3991],
        [-0.4170, -0.1862]])

In [ ]:
beta = 0.7456
beta

0.7456

In [ ]:
torch.mul(x,beta)

tensor([[ 1.0078, -0.2976],
        [-0.3109, -0.1388]])

In [ ]:
torch.add(x,beta,intercept)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1174.)
  """Entry point for launching an IPython kernel.


tensor([[ 0.4984, -1.2524],
        [-1.2703, -1.0395]])

In [ ]:
torch.mul(intercept,x)

tensor([[-1.5469,  0.4568],
        [ 0.4773,  0.2131]])

In [ ]:
torch.mul(x,beta)

tensor([[ 1.0078, -0.2976],
        [-0.3109, -0.1388]])

In [ ]:
## y = intercept + (beta * x)
torch.add(torch.mul(intercept,x),torch.mul(x,beta)) # tensor y

tensor([[-0.5391,  0.1592],
        [ 0.1663,  0.0743]])

In [ ]:
# how to round up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [ ]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [ ]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [ ]:
# truncate the values in a range say 0,1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [ ]:
#truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [ ]:
#truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [ ]:
#scalar division
torch.div(x,0.10)

tensor([[13.5168, -3.9914],
        [-4.1705, -1.8621]])

In [ ]:
#compute the exponential of a tensor
torch.exp(x)

tensor([[3.8639, 0.6709],
        [0.6590, 0.8301]])

In [ ]:
np.exp(x)

tensor([[3.8639, 0.6709],
        [0.6590, 0.8301]])

In [ ]:
#how to get the fractional portion of each tensor

In [ ]:
torch.add(x,10)

tensor([[11.3517,  9.6009],
        [ 9.5830,  9.8138]])

In [ ]:
torch.frac(torch.add(x,10))

tensor([[0.3517, 0.6009],
        [0.5830, 0.8138]])

In [ ]:
# compute the log of the values in a tensor

In [ ]:
x

tensor([[ 1.3517, -0.3991],
        [-0.4170, -0.1862]])

In [ ]:
torch.log(x) #log of negatives are nan

tensor([[0.3013,    nan],
        [   nan,    nan]])

In [ ]:
# to rectify the negative values do a power tranforamtion
torch.pow(x,2)

tensor([[1.8270, 0.1593],
        [0.1739, 0.0347]])

In [ ]:
# rounding up similar to numpy

In [ ]:
x

tensor([[ 1.3517, -0.3991],
        [-0.4170, -0.1862]])

In [ ]:
np.round(x)

tensor([[1., -0.],
        [-0., -0.]])

In [ ]:
torch.round(x)

tensor([[1., -0.],
        [-0., -0.]])

In [ ]:
# how to compute the sigmoid of the input tensor

In [ ]:
x

tensor([[ 1.3517, -0.3991],
        [-0.4170, -0.1862]])

In [ ]:
torch.sigmoid(x)

tensor([[0.7944, 0.4015],
        [0.3972, 0.4536]])

In [ ]:
# finding the square root of the values

In [ ]:
x

tensor([[ 1.3517, -0.3991],
        [-0.4170, -0.1862]])

In [ ]:
torch.sqrt(x)

tensor([[1.1626,    nan],
        [   nan,    nan]])

In [37]:
# Create a tensor
x = torch.arange(10, 10000, 150)
x

tensor([  10,  160,  310,  460,  610,  760,  910, 1060, 1210, 1360, 1510, 1660,
        1810, 1960, 2110, 2260, 2410, 2560, 2710, 2860, 3010, 3160, 3310, 3460,
        3610, 3760, 3910, 4060, 4210, 4360, 4510, 4660, 4810, 4960, 5110, 5260,
        5410, 5560, 5710, 5860, 6010, 6160, 6310, 6460, 6610, 6760, 6910, 7060,
        7210, 7360, 7510, 7660, 7810, 7960, 8110, 8260, 8410, 8560, 8710, 8860,
        9010, 9160, 9310, 9460, 9610, 9760, 9910])

In [38]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 10
Maximum: 9910
Mean: 4960.0
Sum: 332320


In [43]:
torch.argmax(x),torch.argmin(x)

(tensor(66), tensor(0))

In [44]:
torch.max(x),torch.min(x)

(tensor(9910), tensor(10))

In [61]:
# how to change data type
y = torch.tensor([[39,339.63],
[36,667.20],
[33,978.07],
[31,897.13],
[29,178.19],
[26,442.25],
[24,314.22],
[21,547.88],
[18,764.25],
[16,588.23],
[13,773.61]],dtype=torch.float32)

In [62]:
y.dtype 

torch.float32

In [64]:
# Create a float16 tensor
tensor_float16 = y.type(torch.float16)
tensor_float16

tensor([[ 39.0000, 339.7500],
        [ 36.0000, 667.0000],
        [ 33.0000, 978.0000],
        [ 31.0000, 897.0000],
        [ 29.0000, 178.2500],
        [ 26.0000, 442.2500],
        [ 24.0000, 314.2500],
        [ 21.0000, 548.0000],
        [ 18.0000, 764.0000],
        [ 16.0000, 588.0000],
        [ 13.0000, 773.5000]], dtype=torch.float16)

In [59]:
y

tensor([[ 39.0000, 339.6300],
        [ 36.0000, 667.2000],
        [ 33.0000, 978.0700],
        [ 31.0000, 897.1300],
        [ 29.0000, 178.1900],
        [ 26.0000, 442.2500],
        [ 24.0000, 314.2200],
        [ 21.0000, 547.8800],
        [ 18.0000, 764.2500],
        [ 16.0000, 588.2300],
        [ 13.0000, 773.6100]])

In [65]:
# Create a int8 tensor
tensor_int8 = y.type(torch.int8)
tensor_int8


tensor([[  39,   83],
        [  36, -101],
        [  33,  -46],
        [  31, -127],
        [  29,  -78],
        [  26,  -70],
        [  24,   58],
        [  21,   35],
        [  18,   -4],
        [  16,   76],
        [  13,    5]], dtype=torch.int8)

In [68]:
# Change view (keeps same data as original but changes view)
y.view(2,11)

tensor([[ 39.0000, 339.6300,  36.0000, 667.2000,  33.0000, 978.0700,  31.0000,
         897.1300,  29.0000, 178.1900,  26.0000],
        [442.2500,  24.0000, 314.2200,  21.0000, 547.8800,  18.0000, 764.2500,
          16.0000, 588.2300,  13.0000, 773.6100]])

In [96]:
# stacking and unstacking of tensors
A = torch.arange(10,50,5)
B = torch.arange(20,60,5)

In [97]:
A

tensor([10, 15, 20, 25, 30, 35, 40, 45])

In [98]:
torch.stack([A,B],dim=0)

tensor([[10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55]])

In [99]:
torch.stack([A,B],dim=1)

tensor([[10, 20],
        [15, 25],
        [20, 30],
        [25, 35],
        [30, 40],
        [35, 45],
        [40, 50],
        [45, 55]])

In [100]:
torch.stack([A,B])

tensor([[10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55]])

In [104]:
# indexing of tensors
y = torch.stack([A,B,A,B,A,B,A,B])
y

tensor([[10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55],
        [10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55],
        [10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55],
        [10, 15, 20, 25, 30, 35, 40, 45],
        [20, 25, 30, 35, 40, 45, 50, 55]])

In [105]:
# Get all values of 0th dimension and the 1st index of 1st dimension
y[:, 1]

tensor([15, 25, 15, 25, 15, 25, 15, 25])

In [109]:
D = torch.tensor([[[12,13,14],
                   [15,16,17],
                  [18,19,20]]])

In [111]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
D[:, :, 1]

tensor([[13, 16, 19]])

In [112]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
D[:, 1, 1]

tensor([16])

In [113]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
D[0, 0, :] # same as D[0][0]

tensor([12, 13, 14])

In [114]:
D[0][0]

tensor([12, 13, 14])

In [115]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [116]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [117]:
# Count number of devices
torch.cuda.device_count()

0

In [132]:
# x = torch.randn(2, 2, device='cpu') #on cpu
# x = torch.randn(2, 2, device='gpu') #on gpu

# x = torch.randn(2, 2, device=device) #platform agnostic

In [118]:
# flatten tensor like numpy
D.flatten()

tensor([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [125]:
# Concatenate along rows
cat_rows = torch.cat((A, B), dim=0)
cat_rows

tensor([10, 15, 20, 25, 30, 35, 40, 45, 20, 25, 30, 35, 40, 45, 50, 55])

In [129]:
A.reshape(2,4)

tensor([[10, 15, 20, 25],
        [30, 35, 40, 45]])

In [130]:
B.reshape(2,4)

tensor([[20, 25, 30, 35],
        [40, 45, 50, 55]])

In [131]:
cat_cols = torch.cat((A.reshape(2,4), B.reshape(2,4)), dim=1)
cat_cols

tensor([[10, 15, 20, 25, 20, 25, 30, 35],
        [30, 35, 40, 45, 40, 45, 50, 55]])